/** ACTION TYPES */

/** USER ACTION */
export const APP_USER_SET: string = 'APP/USER_SET';
export const APP_USER_UPDATE: string = 'APP/USER_UPDATE';
export const APP_USER_UNSET: string = 'APP/USER_UNSET';

/** LOGIN ACTION */
export const APP_LOGIN: string = 'APP/LOGIN';
export const APP_LOGOUT: string = 'APP/LOGOUT';

/** SOCKET ACTION */
export const APP_SOCKET_IS_CONNECT: string = 'APP/SOCKET_IS_CONNECT';
export const APP_SOCKET_IS_DISCONNECT: string = 'SOCKET_IS_DISCONNECT';

/** USER PLACES ACTION */
export const APP_USER_PLACES_SET: string = 'APP/USER_PLACES_SET';
export const APP_USER_PLACES_UNSET: string = 'APP/USER_PLACES_UNSET';

/** SIDEBAR PLACES ACTION */
export const APP_SIDEBAR_PLACES_SET: string = 'APP/SIDEBAR_PLACES_SET';
export const APP_SIDEBAR_PLACES_UNSET: string = 'APP/SIDEBAR_PLACES_UNSET';

/** UNREAD PLACES ACTION */
export const APP_UNREAD_PLACES_SET: string = 'APP/UNREAD_PLACES_SET';
export const APP_UNREAD_PLACES_UNSET: string = 'APP/UNREAD_PLACES_UNSET';

/** PLACES UNSEEN COUNT ACTION */
export const APP_PLACE_UNSEEN_COUNT_SET: string = 'APP/PLACE_UNSEEN_COUNT_SET';
export const APP_PLACE_UNSEEN_COUNT_UNSET: string = 'APP/PLACE_UNSEEN_COUNT_UNSET';

/** NOTIFICATION ACTION */
export const APP_NOTIFICATION_SET: string = 'APP/NOTIFICATION_SET';
export const APP_NOTIFICATION_UNSET: string = 'APP/NOTIFICATION_UNSET';

/** NOTIFICATION COUNT ACTION */
export const APP_NOTIFICATION_COUNT: string = 'APP/NOTIFICATION_COUNT';

/** LANGUAGE ACTION */
export const APP_LANGUAGE_SET: string = 'APP/LANGUAGE_SET';

/** LIMIT ACTION */
export const APP_LIMITS_SET: string = 'APP/LIMITS_SET';

/** DRAFT ACTION */
export const APP_DRAFT_SET: string = 'APP/DRAFT_SET';
export const APP_DRAFT_UNSET: string = 'APP/DRAFT_UNSET';

/** POSTS ACTION */
export const APP_POSTS_SET: string = 'APP/POSTS_SET';
export const APP_POSTS_UNSET: string = 'APP/POSTS_UNSET';

/** POSTS ACTION */
export const APP_POSTS_ROUTE_SET: string = 'APP/POSTS_ROUTE_SET';
export const APP_POSTS_ROUTE_UNSET: string = 'APP/POSTS_ROUTE_UNSET';

/** CURRENT POST ACTION */
export const APP_CURRENT_POST_SET: string = 'APP/CURRENT_POST_SET';
export const APP_CURRENT_POST_UNSET: string = 'APP/CURRENT_POST_UNSET';
